version: 2

sources:
  - name: finansal_analiz
    database: linen-momentum-476714-g4
    schema: Finansal_analiz 
    tables:
      - name: users_data
      - name: transaction_data
      - name: card_data
      - name: mcc_codes
      - name: zip_code_public
